export const routes = Object.freeze({
  BASE_URL: "/",
  CONTACT_US: "/contact-us",
  SURE_THINGS: "/sure-things",
  OUR_SERVICES: "/our-services",
  BRANDING: "/branding",
  ENGRAVING: "/engraving",
  CUSTOM_MAGNETS: "/magnets/custom-magnets",
  MAGNETS: "/magnets",
  ORDER_PROCESSING: "/order-processing",
  COOL_STUFF: "/cool-stuff",
  BABY_STUFF: "/baby-stuff",
  GADGETS_AND_TECH: "/gadgets-and-tech",
  HOME_STUFF: "/home-stuff",
  PRODUCTS: "/products",
  FRIDGE_MAGNETS: "/magnets/fridge-magnets",
  CAR_MAGNETS: "/magnets/car-magnets",
  PHOTO_MAGNETS: `/magnets/phot0-magnets`,
});
